app <- paste(readLines("app.R",warn=FALSE),collapse="\n")

stopifnot(grepl('record_table_context <- reactiveVal\\(NULL\\)',app,perl=TRUE))
stopifnot(grepl('app_view\\("record_table"\\)',app,perl=TRUE))
stopifnot(grepl('session_can\\("manage_assignments"\\)',app,perl=TRUE))
stopifnot(grepl('allowed_metrics <- c\\("cases","assignments","completed","closed","outstanding","resolved_cases","outstanding_cases","unassigned"\\)',app,perl=TRUE))
stopifnot(grepl('metric %in% c\\("cases","assignments","unassigned","resolved_cases","outstanding_cases"\\)',app,perl=TRUE))
stopifnot(grepl('record_table_link\\(case_total',app,perl=TRUE))
stopifnot(grepl('record_table_link\\(x\\$assigned',app,perl=TRUE))
stopifnot(grepl('record_table_preview\\(r\\$abstract,5L\\)',app,perl=TRUE))
stopifnot(grepl('data-detail.=.?"abstract"',app,perl=TRUE))
stopifnot(grepl('data-detail.=.?"notes"',app,perl=TRUE))
stopifnot(grepl('colspan=if\\(allow_edit\\) "8" else "7"',app,perl=TRUE))
stopifnot(grepl('lem-record-edit',app,fixed=TRUE))
stopifnot(grepl('record_table_edit',app,fixed=TRUE))
stopifnot(grepl('Resolved elsewhere',app,fixed=TRUE))
stopifnot(grepl("Click on 'Completed' to manually edit the responses.",app,fixed=TRUE))
stopifnot(grepl('if\\(abstract_open\\)"▴" else "▾"',app,perl=TRUE))
stopifnot(grepl('if\\(notes_open\\)"▴" else "▾"',app,perl=TRUE))
stopifnot(grepl('record_table_back","Back to main page"',app,fixed=TRUE))
stopifnot(grepl('Rows per page',app,fixed=TRUE))
stopifnot(grepl('record_table_search',app,fixed=TRUE))

cat("PASS: record-table navigation, permissions, drill-downs and expansion controls\n")
